### ISSUE TITLE
Order Switcher by access-date

### ISSUE THREAD

**Issue by gabber235** [jrmoulton/tmux-sessionizer#10]
Currently, when `tms switch` is ran, the order of the sessions is fixed (Alphabetically). It would be really useful if the order changes based on when you opened the last session. 

If one has a lot of sessions open, but is only switching between a small number of them (2 or 3). Then having them be relative based on when you opened allows you to switch much faster between them (especially if you move back and forth between 2 sessions).

**Comment by jrmoulton** [comment]
I think this is something that I don't want to support. I think ordering by access time would be better than just alphabetical order but not sure that it's worth it. It would add quite a bit of complexity to support this. tms doesn't stay running in the background and the access order would need to be cached in a file. And ideally the fuzzy finder is used to get to the right session. I'm not sure there is much benefit to changing this

**Comment by jrmoulton** [comment]
If there was a good implementation I wouldn't have any problem merging a PR for it. As long as it didn't add any noticeable lag and error handling was well done I would merge that

**Comment by jrmoulton** [comment]
coming back to this. I think I was too quick to shut down the idea. This would be a good feature and there's no reason it couldn't be done well
