### ISSUE TITLE
Create new directory/project

### ISSUE THREAD

**Issue by RazoBeckett** [jrmoulton/tmux-sessionizer#114]
Is there a way to create a new directory or project at a specific path? For example, I have a project called "aabbcc" located in the path ~/project/aabbcc. Is it possible to:

1. Determine the parent directory of the project (in this case, ~/project) where the cursor is currently pointing in a list.
2. Provide a pop-up or another method to create a new directory within that path.

**Comment by junglerobba** [comment]
Hi @RazoBeckett,
Does https://github.com/jrmoulton/tmux-sessionizer/commit/a94fe1471f51992f0308de264a2ce19608b7928b cover enough of your usecase? It’s a rather simplistic implementation compared to what you described, but it’s certainly all that I would ever use it for.

**Comment by RazoBeckett** [comment]
Hey @junglerobba,
Thanks for responding to this. I'll check it out when I have some free time and will close the issue then.

**Comment by RazoBeckett** [comment]
it's not same as i wanted though but i can't ask for much it's better than nothing.
Thanks, Closing the issue.

**Comment by junglerobba** [comment]
Hey, I made another update in b23e8a0bfb1ae6a131b26e5d8d7611703640b9ad
Maybe check out if that is closer to what you wanted

**Comment by RazoBeckett** [comment]
Thank you, I really appreciate your work. However, the implementation isn't quite what I expected for this feature.

Here's how I envision it working:
For example, if I have a project located at `~/Dev/personal/my-project`, and I open `tms`, the output should be:

output:
```
 some-other-project
 my-project
>another-project
```

now i move my cursor to the my-project:
output:
```
 some-other-project
>my-project
 another-project
```

Then, by pressing a keybind or shortcut (e.g., `Ctrl+Shift+I`) a pop-up or something similar should come up so that user can enter a name for project then a new repository should be initialized under the same parent directory as `my-project` (which is `personal` in this case). The path for the new repository should be `~/Dev/personal/name-provided-by-user-for-project`.

**Comment by junglerobba** [comment]
The way the feature is implemented right now you could achieve basically the same result, just with different steps.
Assuming you have `~/Dev/personal` configured in your search paths, which it should be if tms is showing projects located there:
You'd run `tms init-repo <name>`, then either
 - if `~/Dev/personal` is the only configured search path, `~/Dev/personal/<name>` will be created and a session opened there
 - if you have multiple search paths configured, a picker would open up showing 
 ```
 >~/Dev/personal
  ...<other dirs>
```
When selecting the directory, `~/Dev/personal/<name>` will be created and a session opened there.
So I'm sorry, but I fail to see the relevant difference, besides the order of steps
