### ISSUE TITLE
Tag a new release

### ISSUE THREAD

**Issue by junglerobba** [jrmoulton/tmux-sessionizer#123]
Hi, can we maybe tag a new release soon-ish? It’s been a few months and quite a few nice features have been added since.
Main reason I’m asking is because I’d like to package tms for homebrew, but the latest release does not contain shell completions yet 😄
(Also a reminder to update Cargo.lock when updating the version to not break the nix package)
Thanks!

**Comment by jrmoulton** [comment]
Sorry I took so long getting this done. Release is out now. Hopefully I've done it right this time (although I always seem to miss something).

**Comment by junglerobba** [comment]
No problem at all, thank you!
It’s already on homebrew (including shell completions) and I’ve submitted a PR to nixpkgs
