### ISSUE TITLE
not working properly with git worktrees?

### ISSUE THREAD

**Issue by mrcjkb** [jrmoulton/tmux-sessionizer#13]
Thanks for this awesome tool!

Unfortunately, it does not seem to work with [git worktrees](https://git-scm.com/docs/git-worktree):

Given a git repository with multiple worktrees
When I call `tms` and select a worktree

### Expected
Then tmux enters a session with the cwd set to the path of the worktree according to `git worktree list`

### Actual
Then tmux enters a session with the cwd set to  `<path-to-main-branch>/.git/worktrees`

**Comment by mrcjkb** [comment]
This is my config:

```
tms config -s main -p /home/mrcjk/git --full-path true
```

**Comment by jrmoulton** [comment]
It does work with git worktrees (this was my main motivation for building tms) but it doesn’t currently let you select between worktrees, you just open a repository (opens in a new session) and it will open all git worktrees that are found in that repository in new tmux windows. 

Is that behavior not working for you?

If you want to be able to select a specific work tree that shouldn’t be too much work as all of the pieces are in place

**Comment by mrcjkb** [comment]
Hmm, maybe I don't understand the workflow with worktrees.

I run `tms` and it lists all of the worktrees.

If I select the `master` branch, it puts me in that directory. But the session only has one window. 

```console
> tmux ls
master: 1 windows (created Wed Jun 14 09:18:10 2023) (attached)
```

If I select a worktree, it puts me in `<path>/master/.git/worktrees` and the session also only has one window.

```console
> tmux ls
master: 1 windows (created Wed Jun 14 09:18:10 2023)
test: 1 windows (created Wed Jun 14 09:27:31 2023) (attached)
```

**Comment by mrcjkb** [comment]
I figured it out: `tms` only works with bare repos.
My repo had a main worktree (not a bare repo) and a bunch of linked worktrees.
I converted it to a bare repo and now it works.
