### ISSUE TITLE
Bookmarks feature

### ISSUE THREAD

**Issue by junglerobba** [jrmoulton/tmux-sessionizer#132]
This is more of a draft of an idea at this point, but especially for times when I'm switching between a small number of projects frequently, it would be really nice to be able to bookmark certain projects to be able to jump to them directly using a single hotkey.
The way I envision it right now is that in my tmux config, I would bind e.g. 4 keys to open bookmarks 1-4, and then either via the config file or maybe even by running `tms bookmark set 2` in a git repo, that repo would get assigned to that number and I could open it directly by using my hotkey bound to bookmark 2.
Is this something that would be useful to other people? Are there any alternative suggestions for something similar? I would be open to implementing it, but I'd like to have these answered first before getting started.

**Comment by petersimonsson** [comment]
I just put up a pull request to implement #90 which could be used to implement this. Maybe not as cleanly as you'd have to edit your tmux config when you want to change a bookmark.

**Comment by jrmoulton** [comment]
I think this feature is in scope. I probably wouldn't use it personally as I like to use the switcher but I would accept a PR.
