### ISSUE TITLE
Tmux doesn't resize panes when terminal window resizes

### ISSUE THREAD

**Issue by Sveske-Juice** [jrmoulton/tmux-sessionizer#14]
When using `tms` command and enter the project it works fine:
![image](https://github.com/jrmoulton/tmux-sessionizer/assets/66884216/e78cc890-d51f-4cde-b7b3-fd7f4ef40beb)

But if I resize the terminal window, tmux doesn't update:
![image](https://github.com/jrmoulton/tmux-sessionizer/assets/66884216/91bf1777-d47e-40d3-8106-8554dcdb5daa)

This can manually be fixed by detaching from the session `prefix` + `d` and then attaching again `$ tmux attach`.

I've tested and this also happens when using the default `tmux.conf`

When i try to manually run the commands that gets executed in the source code (`main.rs`) it works and resizes probably!
```
$ tmux new-session -ds NGJ-VR-2023 -c Documents/Unity/Projects/NGJ-VR-2023
$ tmux new-window -t NGJ-VR-2023 -n idk_this_name -c Documents/Unity/Projects/NGJ-VR-2023
$ tmux kill-window -t NGJ-VR-2023:^
$ tmux switch-client -t idk_this_name
no current client
$ tmux attach -t NGJ-VR-2023
``` 

So I'm not sure if this is because when it gets launched from rust it's in a different environment and then it doesn't work somehow.

**Comment by jrmoulton** [comment]
Maybe the speed that tmux-sessionizer sends the commands makes this bug appear or it might be something else that tmux-sessionizer is doing that causes the bug to appear. So there might be a hacky way around it but at the end of the day I believe the bug is in tmux

**Comment by Sveske-Juice** [comment]
> this is either a bug in tmux or the terminal emulator

Yes that's also what i think since the tmux commands doesn't seem to be the issue

**Comment by Sveske-Juice** [comment]
I've tested on these terminals:

* Alacritty
* xterm
* konsole

I've also tested in a raw tty. The issue persists on all of them. Seems more reasonably it's a bug with tmux

**Comment by jrmoulton** [comment]
Closing for now. If someone finds that this isn't actually a bug in tmux, feel free to reopen
