### ISSUE TITLE
popup window not work when tmux was launched by .zshrc

### ISSUE THREAD

**Issue by xixiaofinland** [jrmoulton/tmux-sessionizer#17]
In my `.zshrc`, I defined a default tmux session to be auto-launched when zsh shell is opened.
The `tms` and `tms sessions` popup windows do not work in this auto-launched tmux session nor any new sessions created after.

If I remove this from `.zshrc`, kill all existing sessions, and manually create a tmux session, the popups show correctly.

```
# Launch tmux automatically in .zshrc
tmux new-session
```

**Comment by kbwhodat** [comment]
How do you resolve this issue? I'm actually facing the same problem

**Comment by jrmoulton** [comment]
@kbwhodat Can you open other tmux popup windows or is it just the tms popup windows that don't open when others do?

**Comment by xixiaofinland** [comment]
i didn't resolve it. I removed it from the .zsh.
