### ISSUE TITLE
skim panic when running from nvim

### ISSUE THREAD

**Issue by hmrc87** [jrmoulton/tmux-sessionizer#25]
I have installed it on my silicon Mac with Kitty and it works fine in terminal. Whenever I open nvim in tmux session and try to run it, it will fail with

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: IOError(Os { code: 6, kind: Uncategorized, message: "Device not configured" })', /Users/myusername/.cargo/registry/src/ind
ex.crates.io-6f17d22bba15001f/skim-0.9.4/src/lib.rs:317:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by jrmoulton** [comment]
Strange. Looks like an upstream error in skim. I'm running short on time (I've got a few PRs I still need to review) and I'm not sure I'll get around to fixing this soon. But what I would like to do is switch to using https://github.com/helix-editor/nucleo
for fuzzy finding. I don't know if it would fix this issue but either way I'll be switching to nucleo at some point and I don't know if there is much reason to fix it in upstream skim.

**Comment by jrmoulton** [comment]
@hmrc87 
We've switched to using nucleo now. I'd be interested to know if this is working now or not.

**Comment by jrmoulton** [comment]
Since we've completely switched to nucleo for fuzzy finding I'm going to close this issue. If a similar problem now exists with nucleo a new issue would be awesome.
