### ISSUE TITLE
New session not being created on dirname clashes

### ISSUE THREAD

**Issue by Forsee41** [jrmoulton/tmux-sessionizer#26]
I have several git repos with same dirnames. I have submodules named "backend" and "frontend" on several projects. Since each submodule being its own repo, their names clash with each other. Sessionizer only creates one session with a given name, and then just attaches to the previous one if the dirname of a new session is the same.

One possible solution would be to prefix a session name with the parent dirname if name clash is possible. For example, if you have these repos:

* `project1/frontend`
* `project2/frontend`

you could make sessions with `project1-frontend` and `project2-frontend` names.
Max search depth won't help cause I want these repos to be searched

**Comment by Forsee41** [comment]
Just to clarify, `--full-path` config option only affects dirname appearance in a fzf search window and doesn't affect the name of created session

**Comment by jrmoulton** [comment]
Ah I hadn't considered this use case. This would be great to fix. I've been swamped lately but I'll add this to my backlog of items to take care of. I would also definitely accept a PR that implements your suggestion of having a prefix name before the path. (would need to be careful of how to implement this in the config)

**Comment by Forsee41** [comment]
I'll take a look at this in a week or 2 if noone's gonna take it by then, a bit busy atm. I'll see what I can do

**Comment by appleseedexm** [comment]
I checked the current `main` and that one still clashes.

PR #88 changes the (default?) display of the projects, but still clashes if the folder name is the same:

`projects/project-a/frontend/.git`
`projects/project-b/frontend/.git`

Both would connect to the same session, and fresh tmux sessions were named `frontend` in both cases.
 However, they would be displayed in tms as `frontend` and `project-b/frontend`. 
IMO it would be nicer to use the same display pattern for both projects if there are clashes, but that might be out of scope for this.
