### ISSUE TITLE
I/O Error

### ISSUE THREAD

**Issue by omerxx** [jrmoulton/tmux-sessionizer#27]
I have no idea what I'm doing wrong. Running the tool always throws an I/o error. Even after running the config command. In a repo, outside a repo, in a bear repo, nothing works.
The sessions switcher is cool and that's the only use I'm able to make.
Any tips...?

**Comment by jrmoulton** [comment]
Does the IO error give any additional context?

**Comment by omerxx** [comment]
This is it - regardless of location / config / path
![image](https://github.com/jrmoulton/tmux-sessionizer/assets/12237955/b6ab0378-8241-4237-8c10-d76d33f98da9)

**Comment by jrmoulton** [comment]
Hmm. I bet the issue is with the path of a folder inside of the config. Can you try re-running the config command and make sure that the path to seach is vallid?

**Comment by jrmoulton** [comment]
@omerxx is this still an issue?

**Comment by jrmoulton** [comment]
Closing for now. Feel free to reopen if this is still an issue
