### ISSUE TITLE
Fzf inside tms does not respect global config

### ISSUE THREAD

**Issue by axkirillov** [jrmoulton/tmux-sessionizer#34]
Hello, I have a couple of questions regarding fzf config. It looks like on my setup when used from sessionizer fzf does not respect my global config. Like, for example, I manage my fzf installation and config through smth called home manager, which is based on Nix package manager. I have this line in it:
```nix
defaultOptions = [ "--bind=ctrl-j:accept" ];
``` 
this is the equivalent of setting
```shell
export FZF_DEFAULT_OPTS="--bind=ctrl-j:accept"
``` 
But when using tms or tms switch, fzf does not respect that setting. Do you have any ideas as to why, and could I circumvent this?

**Comment by axkirillov** [comment]
Ah, sorry, after "skimming" through the repository I realized that you use skim instead of fzf 😅

**Comment by axkirillov** [comment]
so I guess to solve this I would have to make [this](https://github.com/jrmoulton/tmux-sessionizer/blob/3f8ee9cd1530cd5fdc91a86a79150ed27f205ffc/src/main.rs#L175C3-L175C3) configurable. Would you accept a PR?

**Comment by jrmoulton** [comment]
@axkirillov I would! But I actually want to switch away from using skim at all. I'd prefer to switch to using nucleo. I have an issue open for that as well. (Though I haven't actually even looked through to see what options nucleo supports.) 

It would be sad to see a nice pr for skim that loses some effort when I switch to nucleo (at some point). 

So preferable would be to help switch to nucleo first but if you made the changes with skim I would definitely want them merged here.

**Comment by jrmoulton** [comment]
I'm going to close this for now because we've switched to nucleo and a custom tui. 
Custom tui config will be added at some point.
