### ISSUE TITLE
ConfyError::BadTomlData after upgrade to 0.3.0

### ISSUE THREAD

**Issue by VV0JC13CH** [jrmoulton/tmux-sessionizer#37]
I can't get tmux-sessionizer running after upgrade to 0.3.0
I receive [confy::ConfyError::BadTomlData](https://docs.rs/confy/0.5.1/confy/enum.ConfyError.html)
```fish
$tms
Error: Config Error
│
╰─▶ Bad TOML data
```
on my
```fish
Distributor ID: Pop
Description:    Pop!_OS 22.04 LTS
Release:        22.04
Codename:       jammy
```
I don't know yet the root cause of issue. Maybe there is a conflict with config from previous version?

I will try follow the docs:
https://rust-cli.github.io/book/tutorial/errors.html#providing-context
https://docs.rs/directories/5.0.1/directories/
and add path to error msg, because I'm still looking for a TOML file 😄

**Comment by jrmoulton** [comment]
Sorry about that!

Yeah must be an incompatible config on version change. I don't have any testing for the configs and I must have missed something. 

The easiest thing to do would be to remove/backup the config file (on linux it should be in XDG HOME /tms/default-config.toml and then rerun the config subcommand.

**Comment by VV0JC13CH** [comment]
Difference of default-config.toml between versions after `tms config -p "/home/wojciech/Projects"` (I had to add `-d 2`, because of permission issues)
```toml
search_paths = ['/home/wojciech/Projects']
```

```toml
search_paths = []

[[search_dirs]]
path = '/home/wojciech/Projects'
depth = 2
```
Lack of `[[search_dirs]]` returns `BadTomlData`
This config was introduced in: https://github.com/jrmoulton/tmux-sessionizer/commit/4a6d3d6cfa1c46a61f63d31cc00a44331c483077 

Not sure yet what to do about it. My config file was in `$HOME/.config/tms/default-config.toml`

**Comment by jrmoulton** [comment]
> When toml file is invalid, it's not possible.

Oof. I'll need to fix that

> From my perspective it's enough to print path to config file, so issue can be solved by user quicker.

yeah that would be good. I'm using error stack for errors in the repository so adding context on the case of bad tool data that gives users the path to the config file would be good

**Comment by VV0JC13CH** [comment]
There is this `confy::get_configuration_file_path` that can be used in ConfigError. I will try to improve err msg later this month, as currently I'm occupied by other activities.
