### ISSUE TITLE
Issues with `tms config` subcommand when installing v0.3.0 release from crates.io

### ISSUE THREAD

**Issue by bamiesking** [jrmoulton/tmux-sessionizer#42]
With a fresh install of tmux-sessionizer (v0.30 using `cargo install tmux-sessionizer`), setting the `--full-path` option to true after specifying search paths erases the search paths:

![Setting search path before full-path option leads to an error when running tms](https://github.com/jrmoulton/tmux-sessionizer/assets/4366608/4b867882-aebd-4b1d-9c0f-f6020e19a38c)

However setting both at the same time is also not possible:

<img src="https://github.com/jrmoulton/tmux-sessionizer/assets/4366608/97004769-6329-458d-b21f-5b75a5517123" width="54%" alt="Setting search path and full-path at the same time leads to a TOML" />

The first issue is fixed by 6675e60, and the second is fixed by 7089d8b but this leaves the release on crates.io in a bit of a funny spot where it's not possible to use full paths without manually editing the config file. @jrmoulton I'm not sure what your threshold is for a new release (e.g. v0.3.1) but it seems like a new release off bbe70ac would fix a few issues.

**Comment by jrmoulton** [comment]
Whoops. I thought I had published those. I'll go ahead and publish a release off of latest main. 

Thanks!
