### ISSUE TITLE
Slow

### ISSUE THREAD

**Issue by jrmoulton** [jrmoulton/tmux-sessionizer#47]
It seems the checks for submodules have added quite a lot of time to start up and it's enough to notice
At some point switching to gitoxide instead of git2 would be a good idea but I'm not sure it would fix the issue. Last time I tried to switch to gitoxide it still didn't have the support for bare repos that was needed

Might also be good to have the submodule check be configurable

![Screenshot 2024-01-18 at 4 31 39 PM](https://github.com/jrmoulton/tmux-sessionizer/assets/13090441/15588b77-06f0-4282-b674-3c917de3546a)

**Comment by petersimonsson** [comment]
Gitoxide seems to still to be missing functionality, so it's currently not an option.

**Comment by jrmoulton** [comment]
Fixed in #51 

start time is now 77 ms for me. Thanks @petersimonsson
