### ISSUE TITLE
Ability to customize picker shortcuts

### ISSUE THREAD

**Issue by junglerobba** [jrmoulton/tmux-sessionizer#76]
Related to https://github.com/jrmoulton/tmux-sessionizer/pull/75
Would there be enough interest/need for this feature?
I’d be willing to give it a shot at implementing it if so, but I can’t promise much with my limited rust experience so far 😅

**Comment by jrmoulton** [comment]
I feel like configurability wouldn't be a bad thing. It's not something I really want personally but I would accept a PR. 

If it's something that you personally want then go for it, otherwise, like you, I'm not sure there is enough interest to spend the time implementing it.

**Comment by junglerobba** [comment]
Just fyi, I went ahead and started anyway just because I was curious to see how something like this could be implemented. I’d say I’m about 70% of the way there, only struggling a bit with the representation of the shortcuts in the config file and how to get serde to cooperate with me. Will see if I can finish it tomorrow.
