### ISSUE TITLE
additional Arg to start tmux session directly without fuzzy finder window?

### ISSUE THREAD

**Issue by Abishevs** [jrmoulton/tmux-sessionizer#90]
Hej! I've been using tms for quite awhile. But one feature that am missing/do not know how to execute is how to open a project given an arg- "path to dir" for making automated scripts. I guess one workaround would be to manually create a tmux session with the proper name? But if tms already does that then it seems like a "dirty fix". At a time my rust skills were beginner like, but now I might at least try to implement that additional argument for tms. Wanted to get insights from the dev himself on possible issues/ and or why it's not a feature of tms?

**Comment by jrmoulton** [comment]
I hadn't implemented it because I didn't see a strong use case for it and It seemed like it would be a pain to enter manually. 

What sort of scripts are you wanting to write?

**Comment by Abishevs** [comment]
It would indeed be inpractical to enter manually. 

Lately I got tired of creating new project dirs and setup code git init etc. Like cargo has new command but say python does not. Am working in project structure dev/type/lang where type is e.g. personal or work & lang e.g. rust, python, C. Every single project has a specific structure license, .gitignore readme src tests etc. script that am building would wrap around other tools like cargo new, custom for python, custom for C. 

So the idea is to have a cli script where user could pass in new --type personal --lang py project_name. And that would create project structure in the dir: dev/personal/python/project_name. Then if I could chain in tms then it would also start a new tmux session. This workflow is quite specific but i got tired of doing it all manually tbh. 

As well as if tms would have that option I could create keyboard shortcuts for dwm to start/attach to frequently used projects. 

I looked briefly around the source code and tbh I have not a clear plan on how this functionality could be implemented. As I said am still quite new to Rust.

**Comment by emilioziniades** [comment]
This could also be done with vanilla tmux: `tmux new-session -s $SESSION_NAME -c $PATH`
Or if you only have the path, then `tmux new-session -s $PATH -c $PATH`

**Comment by jrmoulton** [comment]
Hmm I don't think that tms would be a good fit for initializing projects. As an example I have a little bash script that I use to create new projects that creates the project and then opens the project using tmux directly. 

I think tms is really more for opening and finding projects and some helpers with git and tmux. 

I think the problem your describing would be more elegantly solved with a bash script

**Comment by Abishevs** [comment]
Tms in this scenario would not actually intiliase a project. It would simply start the session for the newly created project but within a script. 

But I heard you all. Gonna add that step with vanilla tmux. Thought was that with tms it would simplify the process as only a single path would be passed to the tms- in the same way as you would chose a session with fuzzy finder but programatically. But if this functionality within tms would use more setup than using vanilla tmux commands then it's not worth the effort. Thanks 😄

**Comment by forsythetony** [comment]
Going to contribute as this is not a closed issue

This was also something I was looking for. I assumed that it would be a feature of this project as it's based on Primagens [tmux-sessionizer](https://github.com/ThePrimeagen/.dotfiles/blob/master/bin/.local/scripts/tmux-sessionizer) and supported in that script.

I'm also jumping constantly between a few active projects and being able to wire them up as is done [here in Primagens tmux.conf](https://github.com/ThePrimeagen/.dotfiles/blob/602019e902634188ab06ea31251c01c1a43d1621/tmux/.tmux.conf#L30-L37) would be incredibly useful.

Thanks for everyone's work on this by the way. Aside from this small issues I've been enjoying it so far 🙂
